### ISSUE TITLE
crash iterate

### ISSUE THREAD

**Issue by kitech** [kitech/go-toxcore#6]
`
fatal error: unexpected signal during runtime execution                                                             
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f519c0521ae pc=0x7f51bad6fb37]                             

runtime stack:
runtime.throw(0xc16daf, 0x2a)
        /usr/lib/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 8 [syscall, locked to thread]:
runtime.cgocall(0xade910, 0xc42085be50, 0x441522)
        /usr/lib/go/src/runtime/cgocall.go:131 +0x8b fp=0xc42085be20 sp=0xc42085bde8
github.com/kitech/go-toxcore._Cfunc_tox_iterate(0x3511480, 0x0)
        github.com/kitech/go-toxcore/_obj/_cgo_gotypes.go:1589 +0x63 fp=0xc42085be50 sp=0xc42085be20
github.com/kitech/go-toxcore.(*Tox).Iterate.func1(0x3511480, 0x0)
        /home/gzleo/oss/src/github.com/kitech/go-toxcore/tox.go:687 +0x78 fp=0xc42085be88 sp=0xc42085be50
github.com/kitech/go-toxcore.(*Tox).Iterate(0xc42001c1e0)
        /home/gzleo/oss/src/github.com/kitech/go-toxcore/tox.go:687 +0x90 fp=0xc42085beb0 sp=0xc42085be88
main.(*ToxAgent).Iterate(0xc4200703c0)
        /home/gzleo/oss/src/go-purple/yobot/toxagent.go:447 +0x159 fp=0xc42085bfd8 sp=0xc42085beb0
runtime.goexit()

`

**Comment by kitech** [comment]
好像是在删除groupNumber > 0 并且该group是受邀请加入的群时，程序崩溃。

**Comment by kitech** [comment]
好像是受邀的group类型为GROUPCHAT_AV时出现的。
可能是av函数的相关binding还不完善。

**Comment by kitech** [comment]
还是不对啊，被邀请的group类型为GROUPCHAT_TEXT时也DelGroupChat也会崩溃啊。
